### ISSUE TITLE
PhysicalLink: get_connected_physical_ports does not work

### ISSUE THREAD

**Issue by stephanelacrampe** [labs4capella/python4capella#163] opened 2022-11-09 15:51 UTC
In Capella.py:
PhysicalLink: get_connected_physical_ports does not work.
The method it calls on the java Object does not exist (getConnectedPhysicalPorts).
I see 2 methods that corresponds to it: 
getSourcePhysicalPort
getTargetPhysicalPort

**Comment by ylussaud** [comment] 2023-05-03 09:27
Duplicate of #115 which is fixed.

**Closed by ylussaud** 2023-05-03 09:27 UTC
Labels: P2
